@TransactionService_Web_HostAddress = https://localhost:6001

### Get weather forecasts
GET {{TransactionService_Web_HostAddress}}/api/WeatherForecasts
Authorization: Bearer {{access_token}}

### Example login
# POST {{TransactionService_Web_HostAddress}}/api/Account/Login
# Content-Type: application/json
#
# {
#   "email": "administrator@localhost",
#   "password": "Administrator1!"
# }
