<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TransactionService.Domain</RootNamespace>
    <AssemblyName>TransactionService.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
